// Auto-generated by build:manuals — do not edit manually.
export const manualsMeta = {
  "mayhem": { title: "Obozy – Mayhem | Instrukcja | Obozy - Gra Terenowa", description: "Gra alternatywna dla Obozy - Gra Terenowa, zaprojektowana dla agresywniejszej dynamiki walki faworyzującej taktykę grupową.", image: "https://obozy.org.pl/manual-assets/mayhem/icons8-torii-100.png", imageAlt: "Obozy – Mayhem" }
}
