// Auto-generated by build:manuals — do not edit manually.
export const manualsMeta = {
  "mayhem": { title: "Obozy – Mayhem | Instrukcja | Obozy - Gra Terenowa", description: "Gra alternatywna dla Obozy - Gra Terenowa, zaprojektowana dla agresywniejszej dynamiki walki faworyzującej taktykę grupową." },
  "classic": { title: "Obozy – Bullshit | Instrukcja | Obozy - Gra Terenowa", description: "Jakiś losowy tekst do testowania." }
}
